server.address=0.0.0.0
server.port=${PORT:6060}

# DATABASE
spring.datasource.url=jdbc:postgresql://shuttle.proxy.rlwy.net:25657/railway?user=postgres&password=ObkHKaLcutWpduowjLvmannYfeOkrxGM
spring.datasource.driver-class-name=org.postgresql.Driver

# ITO ANG MAGPAPAGAAN NG APP MO
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# LIMITAHAN ANG MEMORY USAGE
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=60000

# BAWASAN ANG THREADS
server.tomcat.threads.max=10
server.tomcat.threads.min-spare=2

# I-DISABLE ANG MGA HINDI KAILANGAN
spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=false

# EMAIL (iwan lang)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=furrealdcs@gmail.com
spring.mail.password=gdcykpechyeqawmp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# CORS
spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true

logging.level.org.springframework.web=ERROR
logging.level.org.hibernate=ERROR
