server.port=8080
server.address=0.0.0.0
server.tomcat.threads.max=5
server.tomcat.threads.min-spare=1
server.tomcat.accept-count=5

spring.datasource.url=jdbc:postgresql://shuttle.proxy.rlwy.net:25657/railway?user=postgres&password=ObkHKaLcutWpduowjLvmannYfeOkrxGM
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
